"""add ntin templates

Revision ID: 0ebd0d94a0b8
Revises: 098098028bfe
Create Date: 2026-07-15 20:34:04.767017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ebd0d94a0b8'
down_revision: Union[str, Sequence[str], None] = '098098028bfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_seller_settings', sa.Column('tpl_country', sa.String(length=128), nullable=True))
    op.add_column('user_seller_settings', sa.Column('tpl_brand', sa.String(length=256), nullable=True))
    op.add_column('user_seller_settings', sa.Column('tpl_unit', sa.String(length=32), nullable=True))
    op.add_column('user_seller_settings', sa.Column('tpl_qty', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_seller_settings', 'tpl_qty')
    op.drop_column('user_seller_settings', 'tpl_unit')
    op.drop_column('user_seller_settings', 'tpl_brand')
    op.drop_column('user_seller_settings', 'tpl_country')
    # ### end Alembic commands ###
