"""add oktru and nkt_request_id

Revision ID: 545a293ecfd7
Revises: 6b19178641a7
Create Date: 2026-07-01 16:41:28.419559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '545a293ecfd7'
down_revision: Union[str, Sequence[str], None] = '6b19178641a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ntin_products', sa.Column('oktru_code', sa.String(length=64), nullable=True, comment='ОКТРУ category code for НКТ, e.g. 1106-0001-0001-100011943'))
    op.add_column('ntin_products', sa.Column('nkt_request_id', sa.Integer(), nullable=True, comment='ID of the request (заявка) in НКТ API — used for status tracking'))
    op.create_index(op.f('ix_ntin_products_nkt_request_id'), 'ntin_products', ['nkt_request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ntin_products_nkt_request_id'), table_name='ntin_products')
    op.drop_column('ntin_products', 'nkt_request_id')
    op.drop_column('ntin_products', 'oktru_code')
    # ### end Alembic commands ###
