
"""Add scans_used

Revision ID: 72cc7211946b
Revises: 545a293ecfd7
Create Date: 2026-07-01 22:27:28.375801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72cc7211946b'
down_revision: Union[str, Sequence[str], None] = '545a293ecfd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    if "users" not in inspector.get_table_names():
        # users table is created by the app's Base.metadata.create_all()
        # on first boot (not by a migration) — nothing to alter yet.
        return
    columns = [c["name"] for c in inspector.get_columns("users")]
    if "scans_used" not in columns:
        op.add_column('users', sa.Column('scans_used', sa.Integer(), nullable=False, server_default='0'))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'scans_used')
    # ### end Alembic commands ###
