"""add analytics and waybills usage

Revision ID: 74cd3a4e91c9
Revises: 9b48dcb6eddd
Create Date: 2026-07-14 19:45:33.826627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74cd3a4e91c9'
down_revision: Union[str, Sequence[str], None] = '9b48dcb6eddd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users') as batch_op:
        batch_op.add_column(sa.Column('analytics_used', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('waybills_used', sa.Integer(), server_default='0', nullable=False))
        batch_op.alter_column('hashed_password',
                   existing_type=sa.VARCHAR(length=512),
                   nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users') as batch_op:
        batch_op.alter_column('hashed_password',
                   existing_type=sa.VARCHAR(length=512),
                   nullable=False)
        batch_op.drop_column('waybills_used')
        batch_op.drop_column('analytics_used')
    # ### end Alembic commands ###
