"""Add preorder_days

Revision ID: 8e21bb515537
Revises: a1b2c3d4e5f6
Create Date: 2026-07-24 10:55:21.452648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e21bb515537'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_repricing_rules_user_id'), table_name='repricing_rules')
    op.drop_table('repricing_rules')
    op.drop_index(op.f('ix_repricing_logs_rule_id'), table_name='repricing_logs')
    op.drop_table('repricing_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repricing_logs',
    sa.Column('id', sa.VARCHAR(length=32), nullable=False),
    sa.Column('rule_id', sa.VARCHAR(length=32), nullable=False),
    sa.Column('old_price', sa.FLOAT(), nullable=False),
    sa.Column('new_price', sa.FLOAT(), nullable=False),
    sa.Column('competitor_price', sa.FLOAT(), nullable=False),
    sa.Column('action', sa.VARCHAR(length=32), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['repricing_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repricing_logs_rule_id'), 'repricing_logs', ['rule_id'], unique=False)
    op.create_table('repricing_rules',
    sa.Column('id', sa.VARCHAR(length=32), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=32), nullable=False),
    sa.Column('product_name', sa.VARCHAR(length=512), nullable=False),
    sa.Column('kaspi_sku', sa.VARCHAR(length=128), nullable=False),
    sa.Column('product_url', sa.TEXT(), nullable=True),
    sa.Column('my_merchant_name', sa.VARCHAR(length=256), nullable=True),
    sa.Column('my_current_price', sa.FLOAT(), nullable=False),
    sa.Column('min_price', sa.FLOAT(), nullable=False),
    sa.Column('base_price', sa.FLOAT(), nullable=True),
    sa.Column('step_kzt', sa.INTEGER(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('last_competitor_price', sa.FLOAT(), nullable=True),
    sa.Column('last_checked_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repricing_rules_user_id'), 'repricing_rules', ['user_id'], unique=False)
    # ### end Alembic commands ###
