"""add google_id

Revision ID: 9b48dcb6eddd
Revises: e738c642c672
Create Date: 2026-07-14 18:39:25.091574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b48dcb6eddd'
down_revision: Union[str, Sequence[str], None] = 'e738c642c672'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_id', sa.String(length=64), nullable=True, comment='Google account ID (sub) for OAuth login'))
    with op.batch_alter_table('users') as batch_op:
        batch_op.alter_column('hashed_password',
                   existing_type=sa.VARCHAR(length=512),
                   nullable=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    with op.batch_alter_table('users') as batch_op:
        batch_op.alter_column('hashed_password',
                   existing_type=sa.VARCHAR(length=512),
                   nullable=False)
    op.drop_column('users', 'google_id')
    op.create_table('pool_participants',
    sa.Column('id', sa.VARCHAR(length=32), nullable=False),
    sa.Column('pool_id', sa.VARCHAR(length=32), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=128), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.Column('delivery_city', sa.VARCHAR(length=128), nullable=True),
    sa.Column('delivery_method', sa.VARCHAR(length=64), nullable=True),
    sa.Column('joined_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['pool_id'], ['pools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pool_participants_user_id'), 'pool_participants', ['user_id'], unique=False)
    op.create_index(op.f('ix_pool_participants_pool_id'), 'pool_participants', ['pool_id'], unique=False)
    op.create_table('repricing_logs',
    sa.Column('id', sa.VARCHAR(length=32), nullable=False),
    sa.Column('rule_id', sa.VARCHAR(length=32), nullable=False),
    sa.Column('old_price', sa.FLOAT(), nullable=False),
    sa.Column('new_price', sa.FLOAT(), nullable=False),
    sa.Column('competitor_price', sa.FLOAT(), nullable=False),
    sa.Column('action', sa.VARCHAR(length=32), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['repricing_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repricing_logs_rule_id'), 'repricing_logs', ['rule_id'], unique=False)
    op.create_table('repricing_rules',
    sa.Column('id', sa.VARCHAR(length=32), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=32), nullable=False),
    sa.Column('product_name', sa.VARCHAR(length=512), nullable=False),
    sa.Column('kaspi_sku', sa.VARCHAR(length=128), nullable=False),
    sa.Column('product_url', sa.TEXT(), nullable=True),
    sa.Column('my_merchant_name', sa.VARCHAR(length=256), nullable=True),
    sa.Column('my_current_price', sa.FLOAT(), nullable=False),
    sa.Column('min_price', sa.FLOAT(), nullable=False),
    sa.Column('base_price', sa.FLOAT(), nullable=True),
    sa.Column('step_kzt', sa.INTEGER(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('last_competitor_price', sa.FLOAT(), nullable=True),
    sa.Column('last_checked_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repricing_rules_user_id'), 'repricing_rules', ['user_id'], unique=False)
    op.create_table('pools',
    sa.Column('id', sa.VARCHAR(length=32), nullable=False),
    sa.Column('product_id', sa.VARCHAR(length=32), nullable=False),
    sa.Column('product_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('supplier_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('pool_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('source_url', sa.TEXT(), nullable=True),
    sa.Column('image_url', sa.TEXT(), nullable=True),
    sa.Column('category', sa.VARCHAR(length=128), nullable=True),
    sa.Column('unit_price', sa.FLOAT(), nullable=True),
    sa.Column('weight_per_unit_kg', sa.FLOAT(), nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=128), nullable=True),
    sa.Column('target_quantity', sa.INTEGER(), nullable=False),
    sa.Column('target_amount', sa.FLOAT(), nullable=False),
    sa.Column('current_quantity', sa.INTEGER(), nullable=False),
    sa.Column('current_amount', sa.FLOAT(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=9), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('expires_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pools_status'), 'pools', ['status'], unique=False)
    op.create_index(op.f('ix_pools_product_id'), 'pools', ['product_id'], unique=False)
    # ### end Alembic commands ###
